### ISSUE TITLE
No need for for using 'return' before 'reply'

### ISSUE THREAD

**Issue by msachi** [a-la-node/database-project#56]
You do it a few times, e.g. [here](https://github.com/a-la-node/database-project/blob/master/server/routes.js#L38)

**Comment by tbtommyb** [comment]
I think it's usually so that we don't have to use an else branch after an if statement but you're right that it's redundant there.

**Comment by otajor** [comment]
I would personally encourage you to use `return reply` everywhere to avoid `reply was called twice` errors, since in most cases you don't want to run any more code after you have replied.

As far as I'm aware there is no reason NOT to use `return reply` to immediately return out of the handler upon replying.

**Comment by msachi** [comment]
Fair enough! 👍
